### ISSUE TITLE
Close Tabs with Middle Mouse Click

### ISSUE THREAD

**Issue by MarvinMynx** [samihaddad/vertical-tabs-chrome-extension#7]
N/A

**Comment by samihaddad** [comment]
Sure, this can be added to next release!

**Comment by samihaddad** [comment]
Added this.

**Comment by chaoscreater** [comment]
@samihaddad - can this be re-open again please? The middle click triggers mouse scrolling and it changes the mouse cursor to the scrolling cursor. Basically, you're scrolling the Vertical Tabs menu whenever you middle click. While the tab does close properly, the problem is that you have to click elsewhere to disable the scrolling.

Running this on UnGoogled Chromium.

**Comment by samihaddad** [comment]
Hey @chaoscreater, I opened a new issue #35 to address this.
